In [31]:
import pandas as pd
import os

In [24]:
# Load data 
df = pd.read_csv('../data/raw/data_balita.csv')

# Melihat gambaran besar data
print(f"Dataset ini memiliki {df.shape[0]} baris dan {df.shape[1]} kolom.")
display(df.head())

Dataset ini memiliki 120999 baris dan 4 kolom.

   Umur (bulan) Jenis Kelamin  Tinggi Badan (cm)       Status Gizi
0             0     laki-laki          44.591973           stunted
1             0     laki-laki          56.705203            tinggi
2             0     laki-laki          46.863358            normal
3             0     laki-laki          47.508026            normal
4             0     laki-laki          42.743494  severely stunted

In [25]:
# Cek data null
print("Jumlah Missing Values:")
print(df.isnull().sum())

Jumlah Missing Values:
Umur (bulan)         0
Jenis Kelamin        0
Tinggi Badan (cm)    0
Status Gizi          0
dtype: int64

In [26]:
print(f"\nJumlah Baris Duplikat: {df.duplicated().sum()}")

Jumlah Baris Duplikat: 81574

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120999 entries, 0 to 120998
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Umur (bulan)       120999 non-null  int64
 1   Jenis Kelamin      120999 non-null  str
 2   Tinggi Badan (cm)  120999 non-null  float64
 3   Status Gizi        120999 non-null  str
dtypes: float64(1), int64(1), str(2)
memory usage: 3.7 MB

In [28]:
df.describe()

        Umur (bulan)  Tinggi Badan (cm)
count  120999.000000      120999.000000
mean       30.173803          88.655434
std        17.575119          17.300997
min         0.000000          40.010437
25%        15.000000          77.000000
50%        30.000000          89.800000
75%        45.000000         101.200000
max        60.000000         128.000000

In [29]:
# Menghapus duplikat dan menyimpan ke variabel baru
df_clean = df.drop_duplicates()

print(f"Jumlah data awal: {len(df)}")
print(f"Jumlah data setelah duplikat dihapus: {len(df_clean)}")
print(f"Total baris yang dibuang: {len(df) - len(df_clean)}")

Jumlah data awal: 120999
Jumlah data setelah duplikat dihapus: 39425
Total baris yang dibuang: 81574

In [30]:
# Sesuaikan nama kolom 
if 'Jenis Kelamin' in df_clean.columns:
    print("Variasi label Jenis Kelamin:")
    print(df_clean['Jenis Kelamin'].value_counts())

Variasi label Jenis Kelamin:
Jenis Kelamin
perempuan    20024
laki-laki    19401
Name: count, dtype: int64

In [32]:
# Simpan ke CSV
df_clean.to_csv('../data/clean/data_balita_clean.csv', index=False)
print("Data berhasil dibersihkan dan disimpan di folder data/clean/")

Data berhasil dibersihkan dan disimpan di folder data/clean/